### ISSUE TITLE
CORS issue on deploying Submodel Registry

### ISSUE THREAD

**Issue by abhishekmaha23** [eclipse-basyx/basyx-java-server-sdk#195]
It's a  minor issue, but I assume this is probably something I might be doing wrong.
I've followed the examples, and used the following configuration for my submodel registry.

```yaml
sm-registry:
  image:
    name: eclipsebasyx/submodel-registry-log-mongodb:2.0.0-SNAPSHOT
    pullPolicy: Always
  service:
    port: 8080
  mongodb:
    connectionString: mongodb://test:test@mongodb:27017
  ingress:
    enabled: true
    host: smregistry.basyx.example.com
  config: |-
    logging:
      level:
        org.springframework.web.cors: DEBUG
    servlet:
      headers:
        - path: /**
          values:
            Access-Control-Allow-Origin: "*"
            Access-Control-Allow-Methods: POST,PUT,GET,DELETE,OPTIONS
            Access-Control-Allow-Headers: Content-Type, Accept
            Access-Control-Max-Age: 10000
        - path: /submodel-descriptors
          values:
            Access-Control-Allow-Origin: "*"
            Access-Control-Allow-Methods: POST,PUT,GET,DELETE,OPTIONS
            Access-Control-Allow-Headers: Accept, Content-Type
          methods: 
            - OPTIONS
        - path: /registry/submodel-descriptors/search
          values:
            Access-Control-Allow-Origin: "*"
            Access-Control-Allow-Methods: POST,GET,OPTIONS
            Access-Control-Allow-Headers: Accept, Content-Type
          methods: 
            - OPTIONS
```
This is exactly the same as what I have for my AAS registry

```yaml
aas-registry:
  image:
    name: eclipsebasyx/aas-registry-log-mongodb:2.0.0-SNAPSHOT
    pullPolicy: Always
  service:
    port: 8080
  mongodb:
    connectionString: mongodb://test:test@mongodb:27017
  ingress:
    enabled: true
    host: aasregistry.basyx.example.com
  config: |-
    logging:
      level:
        org.springframework.web.cors: DEBUG
    servlet:
      headers:
        - path: /**
          values:
            Access-Control-Allow-Origin: "*"
            Access-Control-Allow-Methods: POST,PUT,GET,DELETE,OPTIONS
            Access-Control-Allow-Headers: Content-Type, Accept
            Access-Control-Max-Age: 10000
        - path: /shell-descriptors
          values:
            Access-Control-Allow-Origin: "*"
            Access-Control-Allow-Methods: POST,PUT,GET,DELETE,OPTIONS
            Access-Control-Allow-Headers: Accept, Content-Type
          methods: 
            - OPTIONS
        - path: /registry/shell-descriptors/search
          values:
            Access-Control-Allow-Origin: "*"
            Access-Control-Allow-Methods: POST,GET,OPTIONS
            Access-Control-Allow-Headers: Accept, Content-Type
          methods: 
            - OPTIONS
```
(I'm uploading these as a config file for the Spring apps, so it goes to the right place and is picked up properly, as far as I can tell)
Somehow the newest version of AAS-GUI (eclipsebasyx/aas-gui:v2-240125) has CORS issues with the submodel registry, but not the AAS Registry.

Is there something I can change/reconfigure? Is this perhaps being worked upon?
