### ISSUE TITLE
Problems with docker-compose for log-mem components

### ISSUE THREAD

**Issue by stolze-ifak** [eclipse-basyx/basyx-java-server-sdk#199]
I tried to update my docker-compose file according to the updated docker example in the basyx-server-sdk repository. 
I used the following components:

- eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
- eclipsebasyx/aas-registry-log-mem:latest 
- eclipsebasyx/submodel-registry-log-mem:2.0.0-SNAPSHOT
- eclipsebasyx/aas-gui:v2-240125

When I run the compose file, both registries have no entries. An the UI throws the errors:

`Access to fetch at 'http://localhost:4000/api/v3.0.1/shell-descriptors' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

and

`GET http://localhost:4000/shell-descriptors net::ERR_FAILED 404 (Not Found)`

Here is my code
[aas-env-setup - Kopie.zip](https://github.com/eclipse-basyx/basyx-java-server-sdk/files/14140287/aas-env-setup.-.Kopie.zip)

**Comment by aaronzi** [comment]
I looked into your configuration and found some minor issues that need to be corrected in order for this to work:

- The AAS Environment should depend on the two registries to be healthy otherwise the auto-register feature would not work
- You specified the wrong tag for the Docker image of the AAS Registry (this causes the 404 not found)
- You should use the `basyx.externalurl` when using a port other than 8081 for the AAS Environment
- Also keep in mind that the newest version of docker-compose is 3.8 and not 4.27

Here is the updated `docker-compose.yml`:

```yaml
version: "3.8"
services:
    environment:
        image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
        volumes:
            - ./application.properties:/application/application.properties
            - ./aas-test:/application/aas
        ports:
            - 4002:8081
        depends_on:
            aas-registry:
                condition: service_healthy
            sm-registry:
                condition: service_healthy

    aas-registry:
        image: eclipsebasyx/aas-registry-log-mem:2.0.0-SNAPSHOT
        ports:
            - 4000:8080
        volumes:
            - ./aas-registry.yml:/workspace/config/application.yml

    sm-registry:
        image:  eclipsebasyx/submodel-registry-log-mem:2.0.0-SNAPSHOT
        ports:
            - 4001:8080
        volumes:
            - ./sm-registry.yml:/workspace/config/application.yml      

    web-gui:
        image: eclipsebasyx/aas-gui:v2-240125
        ports:
            - 3000:3000
        environment:
            #CHOKIDAR_USEPOLLING: "true"
            VITE_AAS_REGISTRY_PATH: "http://localhost:4000"
            VITE_SM_REGISTRY_PATH: "http://localhost:4001"
            VITE_AAS_REPO_PATH: "http://localhost:4002/shells"
            VITE_SUBMODEL_REPO_PATH: "http://localhost:4002/submodels"
            VITE_CD_REPO_PATH: "http://localhost:4002/concept-descriptions"
            VITE_PRIMARY_COLOR: "#203864"
            #VITE_BASE_PATH: "<base_path>"
        #volumes:
            #- ./logo:/app/src/assets/Logo
            #- <local_path_to_plugins>:/app/src/UserPlugins
```

This is the updated `application.properties` file:

```
server.port=8081
spring.application.name=AAS Environment

basyx.backend=InMemory
basyx.environment=file:aas
basyx.cors.allowed-origins=* 
# http://localhost:3000, http://localhost:8040, http://localhost:8041
basyx.cors.allowed-methods=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD

basyx.aasrepository.feature.registryintegration = http://aas-registry:8080
basyx.submodelrepository.feature.registryintegration = http://sm-registry:8080
basyx.externalurl = http://localhost:4002
```
