### ISSUE TITLE
Registry - RBAC Authorization

### ISSUE THREAD

**Issue by Jasar92** [eclipse-basyx/basyx-java-server-sdk#261]
I have defined env. variables as follows to enable authorization for the aas-registry in the docker-compose.yml [(example file):](https://github.com/eclipse-basyx/basyx-java-server-sdk/blob/main/examples/docker-compose.yml)
```
  aas-registry:
    image: eclipsebasyx/aas-registry-log-mongodb:2.0.0-SNAPSHOT
    ports:
      - 8082:8080
    volumes:
      - ./aas-registry.yml:/workspace/config/application.yml
    environment:
      - basyx.feature.authorization.enabled = true
      - basyx.feature.authorization.type = rbac
      - basyx.feature.authorization.jwtBearerTokenProvider = keycloak
      - basyx.feature.authorization.rbac.file = classpath:rbac_rules.json
      - spring.security.oauth2.resourceserver.jwt.issuer-uri= http://localhost:9010/realms/BaSyx
```
Even though the docker container get created without any errors. When I try to READ using rest API request GET/shell-descriptors, I can read the information without the JWT access token as well.
I am trying to provide access for those who are only authorised via keycloak (using the RBAC file ) to perform the specified actions as follows:
```
[
  {
    "role": "basyx-reader",
    "action": "READ",
    "targetInformation": {
      "@type": "aas-registry",
      "aasId": "aHR0cHM6Ly9hY3BsdC5vcmcvTUlTU1lfQkYxVDAxTFJY"
    }
  },
  {
    "role": "admin",
    "action": ["CREATE", "READ", "UPDATE", "DELETE"],
    "targetInformation": {
      "@type": "aas-registry",
      "aasId": "aHR0cHM6Ly9hY3BsdC5vcmcvTUlTU1lfQkYxVDAxTFJY"
    }
  },
  {
    "role": "basyx-deleter",
    "action": "DELETE",
    "targetInformation": {
      "@type": "aas-registry",
      "aasId": "aHR0cHM6Ly9hY3BsdC5vcmcvTUlTU1lfQkYxVDAxTFJY"
    }
  }
 ]
```
Could you please help me understand what I am doing wrong here?
