### ISSUE TITLE
Unable to Retrieve AAS from MongoDB

### ISSUE THREAD

**Issue by fransiska26** [eclipse-basyx/basyx-java-server-sdk#294]
**Description:**
I am experiencing an issue where the AAS are successfully stored in MongoDB (checked using MongoDB Compass) but cannot be retrieved after a restart of the containers. Here are the detailed steps to reproduce the issue and the relevant configuration files.

**Steps to Reproduce:**
1. Start with an empty ./data-vol directory.
2. Upload an AASX file from the ui- the upload is successful, and data is stored in MongoDB.
3. Shut down the containers and restart the containers.
4. The previously uploaded AAS data is no longer retrievable from the AAS repository. Any attempt to reupload the AASX file will return success, but nothing is shown in the list.

**Configuration Files:**
**1. docker-compose.yaml:**
```
version: '1'
services:
  mongo:
    image: mongo:5.0.10
    # Provide mongo config
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoAdmin
      MONGO_INITDB_ROOT_PASSWORD: mongoPassword
    # Set health checks to wait until mongo has started
    volumes:
      - ./data-vol:/data/db 
    healthcheck:
      test: mongo
      interval: 10s
      start_period: 5s
      retries: 5
    # Maps tcp port to host
    ports:
      - '27017:27017'

  # AAS Environment
  aas-env:
    image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
    container_name: aas-env
    volumes:
      - ./aas:/application/aas
      - ./basyx/aas-env.properties:/application/application.properties
    ports:
      - '8081:8081'
    restart: always
    depends_on:
      aas-registry:
        condition: service_healthy
      sm-registry:
        condition: service_healthy
      mongo:
        condition: service_healthy

  # AAS Registry
  aas-registry:
    image: eclipsebasyx/aas-registry-log-mem:2.0.0-SNAPSHOT
    container_name: aas-registry
    ports:
      - '8082:8080'
    volumes:
      - ./basyx/aas-registry.yml:/workspace/config/application.yml
    restart: always

  # Submodel Registry
  sm-registry:
    image: eclipsebasyx/submodel-registry-log-mem:2.0.0-SNAPSHOT
    container_name: sm-registry
    ports:
      - '8083:8080'
    volumes:
      - ./basyx/sm-registry.yml:/workspace/config/application.yml
    restart: always

  # AAS Web UI
  aas-web-ui:
    image: eclipsebasyx/aas-gui:v2-240515
    container_name: aas-ui
    ports:
      - '3000:3000'
    environment:
      AAS_REGISTRY_PATH: http://localhost:8082/shell-descriptors
      SUBMODEL_REGISTRY_PATH: http://localhost:8083/submodel-descriptors
      AAS_REPO_PATH: http://localhost:8081/shells
      SUBMODEL_REPO_PATH: http://localhost:8081/submodels
      CD_REPO_PATH: http://localhost:8081/concept-descriptions
    restart: always
    depends_on:
      aas-env:
        condition: service_healthy
```
**2. aas-env.properties:**
```
server.port=8081

basyx.backend = MongoDB
#basyx.backend = InMemory
#basyx.environment=file:aas

basyx.cors.allowed-origins=*
basyx.cors.allowed-methods=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
basyx.aasrepository.feature.registryintegration=http://aas-registry:8080
basyx.submodelrepository.feature.registryintegration=http://sm-registry:8080
basyx.externalurl=http://localhost:8081

spring.data.mongodb.host=mongo
spring.data.mongodb.database=aas-env
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.username=mongoAdmin
spring.data.mongodb.password=mongoPassword
```
**3. aas-registry.yml:**
```
basyx:
  cors:
    allowed-origins: '*'
    allowed-methods: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD

spring:
  data:
    mongodb:
      uri: mongodb://mongoAdmin:mongoPassword@localhost:27017
```
**4. sm-registry.yml:**
```
basyx:
  cors:
    allowed-origins: '*'
    allowed-methods: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD

spring:
  data:
    mongodb:
      uri: mongodb://mongoAdmin:mongoPassword@localhost:27017
```
In [this .zip file](https://github.com/eclipse-basyx/basyx-java-server-sdk/files/15435871/AAS_Mongo.zip), I also provide the logs after restart. 
I am not sure if my configuration is correct, could you provide guidance on how to resolve the problem or if any additional configurations are required?
Thanks in advance.
