### ISSUE TITLE
aas-discovery: Changing server.port in application.properties has no effect

### ISSUE THREAD

**Issue by logmanoriginal** [eclipse-basyx/basyx-java-server-sdk#340]
Using [eclipsebasyx/aas-discovery](https://hub.docker.com/r/eclipsebasyx/aas-discovery) `2.0.0-SNAPSHOT` from Jun 19, 2024, when I change `server.port` in `application.properties` to any value other than 8081, the endpoint is not available.

**application.properties**
```
server.port=8084
spring.application.name=AAS Discovery Service
basyx.aasdiscoveryservice.name=aas-discovery-service

basyx.backend=MongoDB

spring.data.mongodb.host=mongo
spring.data.mongodb.database=aas-discovery
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.username=mongoAdmin
spring.data.mongodb.password=mongoPassword

basyx.cors.allowed-origins=*
basyx.cors.allowed-methods=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
```

**docker-compose**
```yml
services:
  mongo:
    # https://hub.docker.com/_/mongo
    image: mongo:5.0.26
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoAdmin
      MONGO_INITDB_ROOT_PASSWORD: mongoPassword
    healthcheck:
      test: mongo
      interval: 10s
      start_period: 5s
      retries: 5
  aas-discovery:
    # https://hub.docker.com/r/eclipsebasyx/aas-discovery
    image: eclipsebasyx/aas-discovery:2.0.0-SNAPSHOT
    ports:
      - "8084:8084"
    volumes:
      - ./aas-discovery/application.properties:/application/application.properties
    depends_on:
      mongo:
        condition: service_healthy
```
