### ISSUE TITLE
[BUG] basyx-dashboard-api with ARM64

### ISSUE THREAD

**Issue by gerberm-at-msg** [eclipse-basyx/basyx-java-server-sdk#401]
**Describe the bug**
basyx-dashboard-api doesn't run at ARM64 Architecture

```
 ✔ Container aas-env                                                                                                                                            Created                                           0.0s 
 ! dashboard-api The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                                   0.0s
```

**To Reproduce**
This comes from the get-started doc
```
  dashboard-api:
    image: aaronzi/basyx-dashboard-api:SNAPSHOT_02
    container_name: dashboard-api
    ports:
      - '8085:8085'
    volumes:
      - ./basyx/aas-dashboard.yml:/application.yml
    restart: always
    depends_on:
      mongo:
        condition: service_healthy

```

1. Go to '.https://basyx.org/get-started/introduction'
2. Generate Package with Dashboard API
3. Run in AMR64/v8 achricture
4. Image not provided for this architecture. Probably a smilar problem as resolved in [issue 387](https://github.com/eclipse-basyx/basyx-java-server-sdk/issues/387) 

**Expected behavior**

**BaSyx (please complete the following information):**
- BaSyx Version [e.g. v1.3, v2.0]
- BaSyx SDK [e.g. Java, C#, Python]
- AAS Version [e.g. DotAAS V2, DotAAS V3]

**Screenshots**

**Used Asset Administration files (.aasx/.json/.xml)**
Please drop your AAS files here that were used when the bug was encountered.

**BaSyx configuration**
Provide details about the configuration you used. If possible, attach the configuration as a .zip file.

**System (please complete the following information):**
 - OS: Debian VM on Mac 
 - CPU architecture: M3 (linux/arm64/v8)

**Additional context**
