### ISSUE TITLE
[BUG] Unable to access from local network

### ISSUE THREAD

**Issue by roberto-lopardo-aimen** [eclipse-basyx/basyx-java-server-sdk#495]
Hello.

When I access the web-ui from the same PC the docker compose is running, everything works just fine. But when I access it from another PC on the same network only the web-ui loads, whenever I click on an asset it errors out.
![image](https://github.com/user-attachments/assets/191118d8-e67d-41a1-9b12-b3ef3a70e903)

I've tried changing the environment variables to localhost, 0.0.0.0 and the server's IP but nothing works:
``` yaml
  aas-web-ui_v2:
    image: eclipsebasyx/aas-gui:v2-240801
    container_name: aas-web-ui_v2
    ports:
      - "3000:3000"
    environment:
      AAS_REGISTRY_PATH: "http://localhost:8082"
      SUBMODEL_REGISTRY_PATH: "http://localhost:8083"
      AAS_DISCOVERY_PATH: "http://localhost:8084"
      AAS_REPO_PATH: "http://localhost:8081/shells"
      SUBMODEL_REPO_PATH: "http://localhost:8081/submodels"
      CD_REPO_PATH: "http://localhost:8081/concept-descriptions"
```

Could you please help me figure out what's going on? Have you tried using the web-ui from another PC?

Thanks in advance, great work!
