### ISSUE TITLE
[BUG] CORS error for `/description` endpoint

### ISSUE THREAD

**Issue by seicke** [eclipse-basyx/basyx-java-server-sdk#607]
**Describe the bug**
The attempt (of the BaSyx aas-gui) to connect to BaSyx components via `/description` endpoint fails with CORS error, although this is configured correctly in the components:

Discovery + Repos (aas-environment):
```
basyx.cors.allowed-origins=*
basyx.cors.allowed-methods=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
```

Registries:
```
basyx:
  cors:
    allowed-origins: "*"
    allowed-methods: "GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD"
```

All of the BaSyx components are affected (aas-discovery, aas-registry, sm-registry, aas-repo, sm-repo, cd-repo)

**Expected behavior**
In case of setting CORS options as mentioned above, no occuring CORS error for connecting to `/description`endpoint from an origin like the BaSyx aas-gui.

**Additional context / Screenshots**
See https://github.com/eclipse-basyx/basyx-aas-web-ui/pull/288
