### ISSUE TITLE
[BUG] Utilizing '#' in submodelId gives REST API error

### ISSUE THREAD

**Issue by sverrefroy** [eclipse-basyx/basyx-java-server-sdk#642]
**Describe the bug**
Utilizing '#' in submodelId gives REST API error when trying POST to /shells/{aasIdentifier}/submodel-refs.  The post response is 400.
However, after performing the POST, error response and all, the submodel is actually registered within the requested Shell

**To Reproduce**
1. Create a new Shell through the POST /shells with body:
```
{
  "idShort": "LZT_20_0126_FB",
  "id": "http://id.abb/aas/DemoSystem1/SubSystem1/FB#LZT_20_0126",
  "assetInformation": {
    "assetKind": "Instance",
    "assetType": "DemoType"
  },
  "modelType": "AssetAdministrationShell"
}
```
2. Create a new submodel through the POST /submodels with body:
```
{
  "idShort": "FunctionBlock",
  "description": [
    {
      "language": "en",
      "text": "This is the submodel for the FunctionBlock."
    }
  ],
  "id": "http://id.abb/aas/DemoSystem1/SubSystem1/FB/LZT_20_0126/submodel/ABC/4/function#LZT_20_0126_FB",
  "kind": "Instance",
  "semanticId": {
    "type": "ExternalReference",
    "keys": [
      {
        "type": "GlobalReference",
        "value": "https://id.abb/SubmodelTemplate/FunctionBlock/0/1"
      }
    ]
  },
  "submodelElements": [
    {
      "idShort": "Name",
      "description": [
        {
          "language": "en",
          "text": "Specifies the name of the function block."
        }
      ],
      "valueType": "xs:string",
      "value": "LZT_20_0126",
      "modelType": "Property"
    },
    {
      "idShort": "Description",
      "description": [
        {
          "language": "en",
          "text": "Describes the purpose or details regarding the function block."
        }
      ],
      "value": [
        {
          "language": "en",
          "text": "Monitoring of analogue process variables"
        }
      ],
      "modelType": "MultiLanguageProperty"
    },
    {
      "idShort": "Type",
      "description": [
        {
          "language": "en",
          "text": "The type of the function block represented."
        }
      ],
      "valueType": "xs:string",
      "value": "MA",
      "modelType": "Property"
    }
  ],
  "modelType": "Submodel"
}
``` 
4. Register the submodel reference in the Shell through the POST /shells/aHR0cDovL2lkLmFiYi9hYXMvRGVtb1N5c3RlbTEvU3ViU3lzdGVtMS9GQiNMWlRfMjBfMDEyNg/submodel-refs with body:
```
{
  "type": "ModelReference",
  "keys": [
    {
      "type": "Submodel",
      "value": "http://id.abb/aas/DemoSystem1/SubSystem1/FB/LZT_20_0126/submodel/ABC/4/function#LZT_20_0126_FB"
    }
  ]
}
```
4. The POST will then respond with status 400
5. Observe the AAS server GUI and see that the submodel reference is actually registered as requested in spite of the status 400

**Expected behavior**
I would expect the POST to return a status 200 as it is clear that the POST was successful.

**BaSyx (please complete the following information):**
See BaSyx configuration

**Screenshots**
NA

**Used Asset Administration files (.aasx/.json/.xml)**
NA

**BaSyx configuration**
```
services:
  aas-env:
    image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
    container_name: aas-env
    environment:
      - SERVER_PORT=8081
    volumes:
      - ./aas:/application/aas
      - ./basyx/aas-env.properties:/application/application.properties
    ports:
      - '8081:8081'
    restart: always
    depends_on:
      aas-registry:
        condition: service_healthy
      sm-registry:
        condition: service_healthy
      mosquitto:
        condition: service_healthy
  aas-registry:
    image: eclipsebasyx/aas-registry-log-mem:2.0.0-SNAPSHOT
    container_name: aas-registry
    ports:
      - '8082:8080'
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./basyx/aas-registry.yml:/workspace/config/application.yml
    restart: always
  sm-registry:
    image: eclipsebasyx/submodel-registry-log-mem:2.0.0-SNAPSHOT
    container_name: sm-registry
    ports:
      - '8083:8080'
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./basyx/sm-registry.yml:/workspace/config/application.yml
    restart: always
  aas-discovery:
    image: eclipsebasyx/aas-discovery:2.0.0-SNAPSHOT
    container_name: aas-discovery
    environment:
      - SERVER_PORT=8081
    volumes:
      - ./basyx/aas-discovery.properties:/application/application.properties
    ports:
      - '8084:8081'
    restart: always
  mosquitto:
    image: eclipse-mosquitto:2.0.15
    container_name: mosquitto
    ports:
      - '1883:1883'
    volumes:
      - ./mosquitto:/mosquitto
    restart: always
    healthcheck:
      test:
        - CMD-SHELL
        - mosquitto_sub -p 1883 -t 'topic' -C 1 -E -i probe -W 3
      interval: 5s
      timeout: 10s
      start_period: 1s
      retries: 3
  aas-web-ui:
    image: eclipsebasyx/aas-gui:SNAPSHOT #eclipsebasyx/aas-gui:v2-240617
    container_name: aas-ui
    ports:
      - '3000:3000'
    environment:
      AAS_REGISTRY_PATH: http://localhost:8082/shell-descriptors
      SUBMODEL_REGISTRY_PATH: http://localhost:8083/submodel-descriptors
      AAS_REPO_PATH: http://localhost:8081/shells
      SUBMODEL_REPO_PATH: http://localhost:8081/submodels
      CD_REPO_PATH: http://localhost:8081/concept-descriptions
      AAS_DISCOVERY_PATH: http://localhost:8084/lookup/shells
    restart: always
    depends_on:
      aas-env:
        condition: service_healthy

```
![Image](https://github.com/user-attachments/assets/e25cefb1-2887-434f-8068-41601383d2eb)

**System (please complete the following information):**
 - OS: Windows 11
 - Docker Desktop 4.36.0 (175267) 
   - Engine: 27.3.1
   - Compose: v2.30.3-desktop.1 

**Additional context**
NA
