### ISSUE TITLE
[BUG] Filter in the In-Memory Variant of the AASRegistry Is Not Applied Correctly

### ISSUE THREAD

**Issue by geso02** [eclipse-basyx/basyx-java-server-sdk#659]
# **Bug: Filter in the In-Memory Variant of the AASRegistry Is Not Applied Correctly**

## **Description**
In the **in-memory variant of the AASRegistry**, the filter for `assetType` and `assetKind` is **not applied correctly**.  
If either filter is set, only the **resources matching the filter criteria should be returned**.  
However, the current implementation **returns entries that do not match the filter**.

### **Key issues:**
- When querying with **`assetKind=INSTANCE`**, **all Asset Administration Shells are returned**, regardless of the `assetType` filter.
- The combination of `assetKind=INSTANCE` and `assetType` is **not being correctly filtered**.
- The `NOTAPPLICABLE` filter does not properly exclude entries that have an `assetKind` set.

---

## **Affected API Endpoint**
According to the **OpenAPI specification**, the following endpoint should correctly apply the filters:

```yaml
paths:
  /shell-descriptors:
    get:
      summary: Returns all Asset Administration Shell Descriptors
      operationId: GetAllAssetAdministrationShellDescriptors
      parameters:
        - $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0.3#/components/parameters/AssetKind'
        - $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0.3#/components/parameters/AssetType'
```
🔹 **Expected behavior:**  
A `GET /shell-descriptors` request with `assetKind` and `assetType` should **return only the matching resources**.  

🔹 **Actual behavior:**  
When querying with `assetKind=INSTANCE`, **all Asset Administration Shells are returned**, regardless of the `assetType` filter.

---

## **Incorrect Behavior in the Current Implementation**
The current implementation of the filter function is not correctly applying both `assetType` and `assetKind`:

```java
private static class DescriptorFilterFunction {
    private final DescriptorFilter filter;

    public boolean matches(AssetAdministrationShellDescriptor descr) {
        AssetKind filterKind = filter.getKind();
        AssetKind targetKind = descr.getAssetKind();

        if (filterKind == null) {
            return true;
        }
        if (filterKind == AssetKind.INSTANCE) {
            return targetKind == AssetKind.INSTANCE;
        } else if (filterKind == AssetKind.NOTAPPLICABLE) {
            return targetKind == null;
        } else if (targetKind != AssetKind.TYPE) {
            return false;
        } else {
            String filterType = filter.getAssetType();
            if (filterType == null) {
                return true;
            }
            String targetType = descr.getAssetType();
            return filterType.equals(targetType);
        }
    }
}
```

### **Problems in the current implementation:**
❌ **`assetType` is only checked if `assetKind=TYPE`, but is ignored for `INSTANCE` and `NOTAPPLICABLE`.**  
❌ **When `assetKind=INSTANCE`, all AAS are returned, even if `assetType` is set.**  
❌ **For `assetKind=NOTAPPLICABLE`, only `assetKind == null` is checked, but `assetType` is ignored.**

---

## **Expected Behavior**
- If **`assetType` is set**, only AAS with exactly that `assetType` should be returned.
- If **`assetKind` is set**, the following rules should apply:
  - `assetKind=TYPE` → Only AAS with `assetKind=TYPE` should be returned.
  - `assetKind=INSTANCE` → Only AAS with `assetKind=INSTANCE` should be returned. (**Currently broken!**)
  - `assetKind=NOTAPPLICABLE` → Only AAS **without an `assetKind` set** should be returned. (**Currently broken!**)
- If **both filters (`assetType` and `assetKind`) are set**, the response **must match both conditions**.

---

## **Actual Behavior**
- **Currently, entries that do not match the filter criteria are also returned.**
- In particular, when querying with **`assetKind=INSTANCE`**, **all AAS are returned**, ignoring `assetType`.
- When using **`assetKind=NOTAPPLICABLE`**, **entries with a set `assetKind` are still returned**, even though they should not be.

---
