### ISSUE TITLE
[BUG]  PATCH /submodels/{submodelId}/$value returns 400 Bad Request

### ISSUE THREAD

**Issue by ptrstn** [eclipse-basyx/basyx-java-server-sdk#685]
**Description:**

Attempting to update a submodel value via the `PATCH /submodels/{submodelId}/$value` endpoint results in a 400 Bad Request response, even when using valid JSON copied directly from the response of `GET /submodels/{submodelId}/$value`.

This issue has been tested using:
- Swagger UI
- `curl`
- Python `requests`

All methods produce the same 400 Bad Request response.

---

**Steps to Reproduce:**

1. Start the BaSyx AAS Environment (see `compose.yaml` below).
2. Upload a valid submodel (e.g., ProductIdentification).
3. Call `GET /submodels/{submodelId}/$value` → ✅ Works.
4. Copy the JSON response and send it back via `PATCH /submodels/{submodelId}/$value` with a minor edit.

---

**Example Request:**

✅ `GET`:

```bash
curl -X 'GET' \
  'http://localhost:8081/submodels/aHR0cHM6Ly9zbWFydGZhY3RvcnkuZGUvc3VibW9kZWxzL2M5YWZhNzAxLTQyMTgtNDYyOC1iNjJjLTQwMjA0YTBmOWYwNg/$value' \
  -H 'accept: application/json'
```

**Response:**

```json
{
  "Identifier": "https://smartfactory.de/shells/0e2e530c-7daf-41df-b58b-bc8640620a63",
  "ProductName": "Semitrailer"
}
```

❌ `PATCH` (same structure):

```bash
curl -X 'PATCH' \
  'http://localhost:8081/submodels/aHR0cHM6Ly9zbWFydGZhY3RvcnkuZGUvc3VibW9kZWxzL2M5YWZhNzAxLTQyMTgtNDYyOC1iNjJjLTQwMjA0YTBmOWYwNg/$value' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{"Identifier":"https://smartfactory.de/shells/36fd4af1-504c-4159-83e5-ad8286ed45c6","ProductName":"Semitrailer_Truck"}'
```

**Result:**

```json
{
  "type": "about:blank",
  "title": "Bad Request",
  "status": 400,
  "detail": "Failed to read request",
  "instance": "/submodels/.../$value"
}
```

---

**Expected Result:**

Submodel value is updated successfully.

**Actual Result:**

400 Bad Request – `"Failed to read request"`

---

**Notes:**

- The request body is valid JSON and matches the format expected by the API.
- Reproducible with all submodels, even the [examples](https://github.com/eclipse-basyx/basyx-java-server-sdk/tree/main/examples/BaSyxMinimal/aas)
- Verified using Swagger UI, `curl`, and Python `requests` – same result in each case.

---

**Environment:**

- `eclipsebasyx/aas-environment:2.0.0-SNAPSHOT`
- `eclipsebasyx/aas-registry-log-mem:2.0.0-SNAPSHOT`
- `eclipsebasyx/submodel-registry-log-mem:2.0.0-SNAPSHOT`

**compose.yaml:**

<details>
<summary>Click to expand</summary>

```yaml
services:
  aas-environment:
    image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
    ports:
      - "8081:8080"
    environment:
      SERVER_PORT: 8080
      BASYX_CORS_ALLOWED_ORIGINS: "*"
      BASYX_CORS_ALLOWED_METHODS: "GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD"
      BASYX_AASREPOSITORY_FEATURE_REGISTRYINTEGRATION: "http://aas-registry:8080"
      BASYX_SUBMODELREPOSITORY_FEATURE_REGISTRYINTEGRATION: "http://submodel-registry:8080"
      BASYX_ENVIRONMENT: file:/application/aas
      BASYX_EXTERNALURL: "http://localhost:8081"
    volumes:
      - ./aas:/application/aas
    depends_on:
      aas-registry:
        condition: service_healthy
      submodel-registry:
        condition: service_healthy

  aas-registry:
    image: eclipsebasyx/aas-registry-log-mem:2.0.0-SNAPSHOT
    ports:
      - "8082:8080"
    environment:
      SERVER_PORT: 8080
      BASYX_CORS_ALLOWED_ORIGINS: "*"
      BASYX_CORS_ALLOWED_METHODS: "GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD"

  submodel-registry:
    image: eclipsebasyx/submodel-registry-log-mem:2.0.0-SNAPSHOT
    ports:
      - "8083:8080"
    environment:
      SERVER_PORT: 8080
      BASYX_CORS_ALLOWED_ORIGINS: "*"
      BASYX_CORS_ALLOWED_METHODS: "GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD"
```

</details>
